In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score,precision_recall_curve
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

In [2]:
df = pd.read_csv('./DATASET - Sheet1.csv')
#connecting the fdata sheet

In [3]:
df.head()
#display the first 5 data of the data

  CROP TYPE SOIL TYPE  REGION TEMPERATURE WEATHER CONDITION  WATER REQUIREMENT
0    BANANA       DRY  DESERT      20-Oct            NORMAL               8.75
1    BANANA       DRY  DESERT      20-Oct             SUNNY              10.25
2    BANANA       DRY  DESERT      20-Oct             WINDY               9.65
3    BANANA       DRY  DESERT      20-Oct             RAINY               0.75
4    BANANA       DRY  DESERT       20-30            NORMAL               9.85

In [4]:
df.info()
#It will describe about the sheet

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2880 entries, 0 to 2879
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CROP TYPE          2880 non-null   object
 1   SOIL TYPE          2880 non-null   object
 2   REGION             2880 non-null   object
 3   TEMPERATURE        2880 non-null   object
 4   WEATHER CONDITION  2880 non-null   object
 5   WATER REQUIREMENT  2880 non-null   float64
dtypes: float64(1), object(5)
memory usage: 135.1+ KB

In [5]:
df['CROP TYPE'].value_counts()
#it will how many data in each crop

BANANA       192
SOYABEAN     192
CABBAGE      192
POTATO       192
RICE         192
MELON        192
MAIZE        192
CITRUS       192
BEAN         192
WHEAT        192
MUSTARD      192
COTTON       192
SUGARCANE    192
TOMATO       192
ONION        192
Name: CROP TYPE, dtype: int64

In [6]:
df.isnull().sum()
#it will define how many value are not there in sheet

CROP TYPE            0
SOIL TYPE            0
REGION               0
TEMPERATURE          0
WEATHER CONDITION    0
WATER REQUIREMENT    0
dtype: int64

In [7]:
x = df[['CROP TYPE','SOIL TYPE','REGION','TEMPERATURE','WEATHER CONDITION']]
y = df[['WATER REQUIREMENT']]
#we are defing the what are to be defined what value to be fine by meachine learimng

In [8]:
from sklearn.model_selection import  train_test_split
from sklearn.preprocessing import LabelEncoder
#it is used to splite which data is to train and test 
# it is used to encode the each by like maping

In [9]:
le = LabelEncoder()
df['CROP TYPE'] = le.fit_transform(df['CROP TYPE'])
df['SOIL TYPE'] = le.fit_transform(df['SOIL TYPE'])
df['REGION'] = le.fit_transform(df['REGION'])
df['TEMPERATURE'] = le.fit_transform(df['TEMPERATURE'])
df['WEATHER CONDITION'] = le.fit_transform(df['WEATHER CONDITION'])
#it is to encode the data from the sheet to train

In [10]:
df['CROP TYPE'].value_counts()
#0-banana like that

0     192
11    192
2     192
9     192
10    192
6     192
5     192
3     192
1     192
14    192
7     192
4     192
12    192
13    192
8     192
Name: CROP TYPE, dtype: int64

In [11]:
df.head()

,CROP TYPE,SOIL TYPE,REGION,TEMPERATURE,WEATHER CONDITION,WATER REQUIREMENT
0,0,0,0,1,0,8.75
1,0,0,0,1,2,10.25
2,0,0,0,1,3,9.65
3,0,0,0,1,1,0.75
4,0,0,0,0,0,9.85

In [12]:
lr = LinearRegression()
#it will start the linear regression

In [13]:
#lr.predict([[]])

In [14]:
x = df[['CROP TYPE','SOIL TYPE','REGION','TEMPERATURE','WEATHER CONDITION']]
y = df[['WATER REQUIREMENT']]

In [15]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)
#it will train and test the value agt ratio of .2

In [16]:
lr.fit(x_train,y_train)
# it will fit the data with the module and train

LinearRegression()

In [17]:
y_pred = lr.predict(x_test)
#it will predict the value

In [18]:
y_pred

array([[ 5.78708714],
       [ 3.39020628],
       [ 7.3495767 ],
       [ 9.54367429],
       [ 4.99873996],
       [ 5.35738201],
       [ 9.61446934],
       [ 2.92460917],
       [ 8.86089831],
       [ 8.99991148],
       [ 7.03121077],
       [ 4.49525328],
       [ 9.62017389],
       [ 9.28887389],
       [ 5.47170771],
       [ 8.36046159],
       [ 5.89404221],
       [ 8.28820502],
       [10.82959902],
       [ 3.85746948],
       [ 1.59515377],
       [ 3.03150077],
       [ 7.36502424],
       [ 4.92071539],
       [ 6.77793536],
       [ 9.18496878],
       [ 9.08211563],
       [ 8.28668004],
       [ 8.35030903],
       [10.14383656],
       [ 8.82626328],
       [10.93675867],
       [ 3.02579622],
       [ 4.06575273],
       [ 6.25268425],
       [ 6.00107493],
       [ 9.14887223],
       [ 5.20298475],
       [ 5.95906925],
       [ 7.02550623],
       [ 4.05712514],
       [ 8.93315488],
       [ 6.03006888],
       [ 5.45731213],
       [ 5.74355649],
       [ 6.35706238],
       [ 5.83041322],
       [ 4.87891429],
       [ 9.5798343 ],
       [ 3.35404626],
       [ 9.95877926],
       [ 6.85185802],
       [10.11490606],
       [ 1.57338935],
       [ 4.48808722],
       [ 6.60422369],
       [ 9.60007375],
       [ 9.36432153],
       [ 4.39552774],
       [ 6.55671805],
       [ 3.38297675],
       [ 8.89553335],
       [ 6.34273026],
       [10.89170303],
       [ 6.89372258],
       [10.79920701],
       [ 7.86121794],
       [ 7.65445967],
       [ 4.32160508],
       [ 3.52769447],
       [ 1.5676848 ],
       [ 5.53679822],
       [ 1.81060308],
       [ 3.70704722],
       [ 2.74770643],
       [ 7.25242809],
       [ 8.00023111],
       [ 7.29422919],
       [ 4.45345218],
       [ 0.67662559],
       [ 6.46249247],
       [ 3.89780907],
       [ 2.63517373],
       [ 3.49876398],
       [ 4.24510548],
       [12.00146609],
       [ 5.67129992],
       [ 6.85583301],
       [ 7.29575417],
       [ 8.96951947],
       [ 7.1365774 ],
       [ 8.5729244 ],
       [ 5.96079881],
       [ 8.99844997],
       [ 3.35557124],
       [ 8.21846193],
       [ 3.89210452],
       [ 5.56990828],
       [ 4.74859216],
       [ 8.19251793],
       [ 8.17659736],
       [ 2.13467355],
       [ 8.66867495],
       [ 6.35413935],
       [ 3.12718786],
       [ 8.24885393],
       [ 7.35925623],
       [ 5.74926103],
       [ 4.92794491],
       [ 9.67803487],
       [ 8.51506342],
       [ 2.88107851],
       [ 4.25087348],
       [ 7.64305058],
       [ 7.53144292],
       [10.68341979],
       [ 9.0360715 ],
       [ 4.49949631],
       [ 8.0116402 ],
       [ 4.13654778],
       [ 8.54551889],
       [ 4.639971  ],
       [ 9.31681589],
       [10.68912434],
       [ 9.2599434 ],
       [ 9.08357714],
       [ 8.7161806 ],
       [ 4.75277173],
       [ 5.56420373],
       [ 5.31982394],
       [ 6.42639592],
       [ 5.03755457],
       [ 4.42870126],
       [ 4.6369845 ],
       [ 4.0514206 ],
       [ 5.99537038],
       [10.33188035],
       [ 5.85065267],
       [ 6.34837134],
       [ 2.16214252],
       [ 0.5954734 ],
       [ 4.67884906],
       [ 7.82512138],
       [ 7.5764351 ],
       [ 5.60773439],
       [10.19286718],
       [ 5.28094587],
       [ 8.10739075],
       [ 7.50397395],
       [ 4.27257445],
       [ 4.56054836],
       [ 8.60510942],
       [ 5.67999096],
       [ 2.77564842],
       [ 6.00259991],
       [ 5.78144605],
       [ 3.34834172],
       [10.82097144],
       [ 8.64544901],
       [ 3.0717769 ],
       [ 2.64950586],
       [12.72458164],
       [ 7.42607629],
       [ 4.84998379],
       [ 3.21649461],
       [ 5.07120111],
       [ 1.3826275 ],
       [ 5.9897293 ],
       [ 7.82804442],
       [10.08027103],
       [11.89138341],
       [ 6.75763245],
       [10.54586814],
       [ 5.71316448],
       [10.75163791],
       [ 7.71398675],
       [12.28472395],
       [ 4.98434437],
       [ 5.12753711],
       [10.30294986],
       [ 7.32468466],
       [ 6.79080597],
       [ 7.28852464],
       [ 8.61075051],
       [ 1.27254482],
       [ 5.85516414],
       [ 8.72341012],
       [ 6.50602313],
       [ 6.2051786 ],
       [ 4.38690016],
       [ 4.0672777 ],
       [ 9.61148284],
       [ 6.66680072],
       [ 5.70745993],
       [ 9.27752826],
       [ 4.38982319],
       [ 8.72188515],
       [ 2.5337821 ],
       [ 3.60266909],
       [ 7.5096785 ],
       [ 8.649424  ],
       [ 4.68031058],
       [10.6126882 ],
       [ 0.91383932],
       [ 7.53860899],
       [ 0.91954387],
       [11.35332515],
       [ 5.49645864],
       [ 4.96974601],
       [ 8.88836729],
       [12.36017159],
       [ 8.11707029],
       [ 6.4667355 ],
       [ 4.53878394],
       [ 5.24729933],
       [ 4.91354932],
       [ 5.17809271],
       [ 2.41694292],
       [ 7.99160353],
       [ 4.78176568],
       [ 5.81601763],
       [ 6.92265307],
       [ 4.2364779 ],
       [ 4.84679272],
       [ 6.32667038],
       [ 8.83196782],
       [ 5.21836884],
       [ 8.93016839],
       [ 8.43397469],
       [ 9.18503224],
       [ 6.09974852],
       [10.89740758],
       [ 5.34875443],
       [ 6.18341418],
       [ 8.7926802 ],
       [12.9039344 ],
       [ 3.92103501],
       [ 8.46755777],
       [ 7.36349926],
       [ 8.7508791 ],
       [ 8.94456398],
       [ 2.7074303 ],
       [ 5.17238817],
       [ 7.64424365],
       [ 9.82275258],
       [ 2.49762208],
       [ 9.54221277],
       [ 6.03869646],
       [ 5.92867724],
       [ 2.82315407],
       [ 9.32822498],
       [ 7.00228028],
       [ 9.97317484],
       [ 9.7648916 ],
       [10.42192635],
       [ 6.43057549],
       [ 7.64869167],
       [ 8.64371945],
       [ 7.00479376],
       [ 4.77752265],
       [ 5.023632  ],
       [ 4.85402225],
       [ 5.16933821],
       [ 5.99689536],
       [10.57479863],
       [ 8.74663607],
       [ 5.77567805],
       [ 3.64202018],
       [ 7.11063341],
       [ 2.71877594],
       [ 5.32281043],
       [11.57301749],
       [ 3.38721978],
       [11.37190031],
       [ 5.27948435],
       [ 4.53565633],
       [ 5.81900413],
       [ 6.75046639],
       [ 2.94783511],
       [10.469432  ],
       [ 7.25806918],
       [ 8.35900007],
       [ 5.5771378 ],
       [ 8.85519377],
       [ 6.28480581],
       [ 3.92826453],
       [ 5.14763725],
       [ 1.96672989],
       [10.57805316],
       [ 9.36286002],
       [ 3.00257028],
       [ 9.85738762],
       [ 7.64006408],
       [ 6.82292753],
       [ 6.57681818],
       [ 4.12686824],
       [ 4.4519272 ],
       [ 5.86657323],
       [ 1.12782711],
       [ 3.27190558],
       [ 6.50283206],
       [ 5.88833766],
       [ 4.76883161],
       [ 2.67849981],
       [12.04180567],
       [ 3.02427125],
       [ 5.2070232 ],
       [ 7.60536559],
       [ 3.890643  ],
       [ 5.70175538],
       [10.28855427],
       [10.00210533],
       [ 3.5205284 ],
       [ 4.95535042],
       [ 7.86844746],
       [ 8.79414171],
       [ 3.87923391],
       [ 4.99004892],
       [ 3.74022074],
       [ 2.87955353],
       [ 3.77957183],
       [10.3261758 ],
       [ 1.59661529],
       [ 1.27824937],
       [ 1.74557604],
       [ 8.9012379 ],
       [ 5.63672834],
       [ 5.06549656],
       [10.71805483],
       [ 7.61259511],
       [ 7.93771754],
       [ 3.66524612],
       [10.54440662],
       [11.0131948 ],
       [10.7863364 ],
       [ 5.33415606],
       [ 3.24548856],
       [ 4.52020878],
       [ 7.36496078],
       [ 4.49127829],
       [ 9.7908356 ],
       [ 7.28135858],
       [ 9.67552139],
       [ 7.60390407],
       [ 7.25236463],
       [ 3.71129025],
       [11.32439466],
       [ 7.11633795],
       [ 9.19067333],
       [ 8.07520573],
       [ 2.49191754],
       [ 7.52892945],
       [ 7.25090311],
       [ 7.14234541],
       [ 8.46185323],
       [10.33041883],
       [ 6.0315304 ],
       [10.64732323],
       [11.55125306],
       [ 5.02767045],
       [ 2.63809677],
       [ 4.10761729],
       [ 9.24289322],
       [ 6.3932224 ],
       [10.18570112],
       [ 2.06394196],
       [ 0.38719015],
       [ 4.07145727],
       [10.57234861],
       [12.93286489],
       [ 4.16150328],
       [ 2.45157795],
       [ 8.79984626],
       [10.24827815],
       [ 2.96070572],
       [ 5.21266429],
       [ 4.46632279],
       [ 2.815988  ],
       [ 9.68122594],
       [ 6.70860182],
       [ 8.17089282],
       [ 3.41913677],
       [ 2.63093071],
       [ 9.31932936],
       [12.75351213],
       [10.92534957],
       [ 8.00593565],
       [ 3.81818186],
       [ 7.71232065],
       [ 2.66556574],
       [ 9.28323281],
       [ 4.92648339],
       [ 4.278279  ],
       [12.18652339],
       [ 7.33032574],
       [ 2.10574306],
       [ 3.56955903],
       [11.53984397],
       [ 9.50584818],
       [ 3.71275177],
       [ 3.96143805],
       [ 1.42867163],
       [ 7.20889743],
       [ 9.43511659],
       [ 6.92683264],
       [ 9.5380332 ],
       [ 5.52240263],
       [ 8.63403991],
       [12.25579346],
       [ 9.71586098],
       [ 9.57114326],
       [12.57986393],
       [ 2.74525641],
       [11.14504191],
       [ 2.1403781 ],
       [10.79204095],
       [ 9.79952664],
       [10.14536153],
       [ 2.71313485],
       [ 8.82877675],
       [ 8.85373225],
       [ 1.56198025],
       [ 9.57684781],
       [ 1.7527421 ],
       [ 6.53641514],
       [ 6.27910127],
       [ 4.53559287],
       [ 6.92981914],
       [ 5.85217765],
       [ 8.68154556],
       [ 8.68300708],
       [ 6.96445418],
       [ 4.27980397],
       [ 7.81218731],
       [ 6.21240813],
       [ 7.19131258],
       [ 7.86274291],
       [ 9.86628324],
       [ 5.45313256],
       [ 5.74674756],
       [ 6.42069137],
       [ 7.75014676],
       [11.82781788],
       [ 4.48557374],
       [ 5.20549823],
       [ 2.10428154],
       [ 8.71764212],
       [ 9.00415451],
       [ 7.27565403],
       [ 6.3234793 ],
       [12.78814717],
       [ 7.4678774 ],
       [ 7.14228195],
       [11.19254756],
       [ 3.0950663 ],
       [ 4.99721498],
       [ 7.39395473],
       [ 9.42941204],
       [ 2.31110327],
       [11.42976129],
       [10.95998461],
       [ 6.92829416],
       [11.00602874],
       [ 0.77482615],
       [ 8.70330999],
       [ 5.49201062],
       [12.42944167],
       [10.29425882],
       [ 5.81754261],
       [ 9.79236057],
       [11.4008308 ],
       [ 8.54253239],
       [ 6.65325432],
       [ 8.5311233 ],
       [10.40434149],
       [ 7.31593016],
       [ 5.42990661],
       [ 9.32252043],
       [ 8.8230722 ],
       [ 4.92224036],
       [ 4.07716182],
       [ 3.53339901],
       [ 7.7180252 ],
       [ 3.52921944],
       [ 8.639681  ],
       [ 9.75620056],
       [ 4.42299671],
       [ 8.02770008],
       [ 6.16908205],
       [ 4.30873447],
       [10.11789256],
       [ 8.4371023 ],
       [ 3.2801236 ],
       [ 6.95728811],
       [ 6.67648026],
       [ 8.29071849],
       [10.53299753],
       [ 7.67616064],
       [11.2157735 ],
       [ 9.0081295 ],
       [ 1.2089793 ],
       [ 2.09287245],
       [ 9.33073845],
       [ 4.96675952],
       [ 3.10070739],
       [ 6.39892694],
       [ 7.25388961],
       [ 6.53077405],
       [10.75740591],
       [ 4.11332183],
       [ 9.03454652],
       [ 1.31858895],
       [ 2.10003851],
       [ 3.84313735],
       [ 2.89812869],
       [ 9.85487414],
       [ 5.13470318],
       [ 5.41697254],
       [ 7.56508946],
       [11.04212529],
       [ 3.98931659],
       [ 4.56353486],
       [ 3.67095067],
       [ 8.04057069],
       [ 7.39144126],
       [ 4.92641993],
       [ 9.42788706],
       [ 9.18748226],
       [ 2.74200188],
       [ 8.79016672],
       [ 9.90091827],
       [ 2.91571355],
       [ 8.65512855],
       [ 4.81215769],
       [12.60879442],
       [ 9.0778726 ],
       [ 5.71468945],
       [ 7.18163304],
       [ 7.85975642],
       [ 9.37002608],
       [ 3.98215052],
       [ 4.95959345],
       [ 6.42633246],
       [ 9.04025107],
       [ 5.57309935],
       [ 7.07307534],
       [ 2.53942319],
       [ 4.77606113],
       [ 9.21966728],
       [ 5.96226032],
       [ 3.91957349],
       [ 3.85030342],
       [ 6.09981198],
       [11.92601845],
       [ 0.74019111],
       [ 3.0010453 ],
       [ 2.2722252 ],
       [ 1.93209485],
       [ 7.85405187],
       [ 4.10038776],
       [ 6.86160102],
       [ 2.6005387 ],
       [ 2.28509581],
       [10.43479696],
       [ 3.95322003],
       [ 1.62978881],
       [ 5.12906209],
       [ 5.14047118],
       [ 8.50935887],
       [ 7.43178084],
       [10.78779792],
       [ 8.27533441],
       [ 5.49493366],
       [ 8.89135378],
       [ 4.16866934],
       [ 7.24519856]])

In [19]:
lr.score(x_test,y_test)

0.027369207432425546

In [20]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [21]:
mean_absolute_error(y_pred,y_test)

3.2527541255251293

In [22]:
mean_squared_error(y_pred,y_test)

15.280969719952857

In [23]:
t = x_test[:5]
t

      CROP TYPE  SOIL TYPE  REGION  TEMPERATURE  WEATHER CONDITION
2332         12          0       2            3                  0
1431          3          1       2            0                  1
1135          6          2       3            3                  1
2601         13          1       3            2                  2
85            0          1       2            0                  2

In [24]:
lr.predict(t)

array([[5.78708714],
       [3.39020628],
       [7.3495767 ],
       [9.54367429],
       [4.99873996]])

In [25]:
lr.predict([[16,1,3,2,1]])
# example given

array([[7.9351406]])